name = input('Введите свое имя: ')
day = int(input('Введите день рождения: '))
mounth = int(input('Введите месяц рождения: '))
year = int(input('Введите год рождения: '))
print(f"меня зовут {name} ,мой день рождения: {day}.{mounth}.{year}")
